apiVersion: v1
kind: Secret
metadata:
  name: cortex-nids-secrets
  namespace: default
type: Opaque
stringData:
  JWT_SECRET_KEY: "cortex_super_secret_jwt_key_998877665544332211_xdr"
  ADMIN_PASSWORD: "AdminPassword123!"
